from typing import Any, Optional

def debug(fmt_str: str, *args: Any) -> None: ...
def get_user_home() -> Optional[str]: ...
def write_to_temp_file(file_path: str, content: str) -> None: ...
def get_abs_path(file_path: str) -> Optional[str]: ...
def open_browser(url: str) -> None: ...
def is_file_exists(file_path: str) -> bool: ...
def read_file(file_path: str) -> str: ...