from typing import Any, Optional

def debug(fmt_str: str, *args: Any) -> None: ...
def get_user_home() -> Optional[str]: ...
def open_browser(url: str) -> None: ...

class FilePath:
    def __init__(self) -> None: ...

    @staticmethod
    def new_with_path(file_path: str) -> FilePath: ...

    def is_file_exists(self) -> bool: ...
    def read_file(self) -> str: ...
    def write_to_temp_file(self, content: str) -> None: ...
    def get_abs_path(self) -> Optional[str]: ...