//! The name, MIME type and conventional extension of every format.
//!
//! Generated by `scripts/gen_kinds.ps1` from the format tables in
//! `readme.md` plus the metadata table at the top of that script. Do not
//! edit by hand; `tests/kinds_meta.rs` holds it against `SIGNATURE_KIND`.
//!
//! The readme is the source for the display names because it is what a reader
//! sees, and a crate whose `Debug` output says `Png` where its documentation
//! says "PNG" has two names for one thing. The MIME types and extensions are
//! in the generator because they are not in the readme and are not derivable
//! from magic bytes: `50 4B 03 04` is a zip container, and whether that is
//! `application/zip` or `application/java-archive` or
//! `application/vnd.android.package-archive` is a question about the bytes
//! *inside* it, which is a longer answer than a magic number.

use crate::magical::magic::FileKind;

/// Every format, in the order the metadata table is sorted.
///
/// Sorted by the short name the Python binding uses as its enum value -- `7z`
/// before `ace` before `amr` -- and by nothing else. It is deliberately not
/// `SIGNATURE_KIND` order, which is the order detection has to try rules in:
/// 71 of its 114 entries are out of enum order, so a catalogue built from it
/// reads as though something were wrong with the formats near the end. Nor is
/// it enum order, which is neither alphabetical nor grouped, and which changed
/// meaning last time a format was added in the section it belonged to.
///
/// A display name, a MIME type or an extension is the stable way to name a
/// format in a table, and a list of those is what a reader can scan.
pub static ALL_KINDS: [FileKind; 114] = [
    FileKind::SevenZip,
    FileKind::AceCompressed,
    FileKind::Aiff,
    FileKind::Amr,
    FileKind::MonkeyAudio,
    FileKind::Arj,
    FileKind::Asf,
    FileKind::AuAudioFileFormat,
    FileKind::Avro,
    FileKind::BLENDER,
    FileKind::Bitmap,
    FileKind::BinaryPlist,
    FileKind::Bzip,
    FileKind::Cabinet,
    FileKind::CoreAudio,
    FileKind::Chm,
    FileKind::Class,
    FileKind::Cpio,
    FileKind::GoogleChromeExtension,
    FileKind::Cursor,
    FileKind::Dds,
    FileKind::Deb,
    FileKind::Dalvik,
    FileKind::Djvu,
    FileKind::AppleDiskImage,
    FileKind::ELF,
    FileKind::MSDOS,
    FileKind::OpenExr,
    FileKind::FbxBinary,
    FileKind::Fits,
    FileKind::Flac,
    FileKind::FlashVideo,
    FileKind::Gguf,
    FileKind::GIF,
    FileKind::GltfBinary,
    FileKind::Gzip,
    FileKind::Hdf5,
    FileKind::NoodlesoftHazel,
    FileKind::Radiance,
    FileKind::AppleIconImage,
    FileKind::ICO,
    FileKind::ISO,
    FileKind::OpenGLIrisPerformer,
    FileKind::JPEG2000,
    FileKind::Jpg,
    FileKind::JpegXl,
    FileKind::Ktx,
    FileKind::Ktx2,
    FileKind::WindowsShortcut,
    FileKind::Lua,
    FileKind::Lz4,
    FileKind::Lzh,
    FileKind::MachO,
    FileKind::Matlab,
    FileKind::Midi,
    FileKind::MatroskaMediaContainer,
    FileKind::Mobipocket,
    FileKind::ModuleForEvenvironmentModules,
    FileKind::MP3,
    FileKind::IsoMedia,
    FileKind::MpegProgramStream,
    FileKind::Numpy,
    FileKind::OGG,
    FileKind::OleCompoundFile,
    FileKind::Orc,
    FileKind::OpenTypeFont,
    FileKind::Par2,
    FileKind::Parquet,
    FileKind::Pcap,
    FileKind::PcapNg,
    FileKind::PhotoCapTemplate,
    FileKind::Pcx,
    FileKind::PDF,
    FileKind::Pickle,
    FileKind::Ply,
    FileKind::Png,
    FileKind::PostScript,
    FileKind::_8BPS,
    FileKind::Qcow,
    FileKind::Qcow2,
    FileKind::RAR,
    FileKind::RData,
    FileKind::RPM,
    FileKind::RichTextFormat,
    FileKind::ScriptExecute,
    FileKind::SerializedJavaData,
    FileKind::StuffitSit,
    FileKind::Slob,
    FileKind::SQLite,
    FileKind::Stuffit,
    FileKind::Swf,
    FileKind::Tar,
    FileKind::Tiff,
    FileKind::BitTorrent,
    FileKind::FontCollection,
    FileKind::TrueTypeFont,
    FileKind::VBScriptEncoded,
    FileKind::VirtualBoxVdi,
    FileKind::VirtualHd,
    FileKind::Vmdk,
    FileKind::CreativeVoiceFile,
    FileKind::DoomWad,
    FileKind::WASM,
    FileKind::WEBP,
    FileKind::WindowImagingFormat,
    FileKind::Woff,
    FileKind::Woff2,
    FileKind::WavPack,
    FileKind::GimpXcf,
    FileKind::XML,
    FileKind::Xz,
    FileKind::PkgZip,
    FileKind::Zlib,
    FileKind::Zstd,
];

impl FileKind {
    /// All four answers at once, in one match.
    ///
    /// One `match` rather than four, because a 114-arm `match` is a hundred lines
    /// long and five of them is five hundred lines of generated code where one
    /// would do -- and five places for a `clippy::too_many_lines` allowance to be
    /// repeated. Four one-line accessors read the tuple.
    ///
    /// `clippy::too_many_lines` is allowed rather than avoided because there is no
    /// way to avoid it: 114 arms is 116 lines. The alternative is an index into a
    /// `static` slice, which trades a lint the tool has a number for a bounds
    /// check on every call.
    #[allow(clippy::too_many_lines)]
    const fn meta(
        self,
    ) -> (
        &'static str,
        Option<&'static str>,
        Option<&'static str>,
        &'static str,
    ) {
        match self {
            Self::SevenZip => (
                "7-Zip",
                Some("application/x-7z-compressed"),
                Some("7z"),
                "SevenZip",
            ),
            Self::AceCompressed => ("ACE archive", None, None, "AceCompressed"),
            Self::Aiff => ("AIFF", Some("audio/aiff"), Some("aiff"), "Aiff"),
            Self::Amr => ("AMR audio", Some("audio/amr"), Some("amr"), "Amr"),
            Self::MonkeyAudio => (
                "Monkey's Audio",
                Some("audio/x-monkeys-audio"),
                Some("ape"),
                "MonkeyAudio",
            ),
            Self::Arj => ("ARJ", Some("application/x-arj"), Some("arj"), "Arj"),
            Self::Asf => ("ASF / WMV", Some("video/x-ms-asf"), Some("asf"), "Asf"),
            Self::AuAudioFileFormat => (
                "AU audio",
                Some("audio/basic"),
                Some("au"),
                "AuAudioFileFormat",
            ),
            Self::Avro => ("Avro", Some("application/avro"), Some("avro"), "Avro"),
            Self::BLENDER => (
                "Blender",
                Some("application/x-blender"),
                Some("blend"),
                "BLENDER",
            ),
            Self::Bitmap => ("Bitmap", Some("image/bmp"), Some("bmp"), "Bitmap"),
            Self::BinaryPlist => (
                "Binary plist",
                Some("application/x-bplist"),
                Some("bplist"),
                "BinaryPlist",
            ),
            Self::Bzip => ("Bzip2", Some("application/x-bzip2"), Some("bz2"), "Bzip"),
            Self::Cabinet => (
                "Cabinet",
                Some("application/vnd.ms-cab-compressed"),
                Some("cab"),
                "Cabinet",
            ),
            Self::CoreAudio => ("Core Audio", Some("audio/x-caf"), Some("caf"), "CoreAudio"),
            Self::Chm => (
                "MS Compiled HTML",
                Some("application/vnd.ms-htmlhelp"),
                Some("chm"),
                "Chm",
            ),
            Self::Class => (
                "Java class",
                Some("application/java-vm"),
                Some("class"),
                "Class",
            ),
            Self::Cpio => ("cpio", Some("application/x-cpio"), Some("cpio"), "Cpio"),
            Self::GoogleChromeExtension => (
                "Chrome extension",
                Some("application/x-chrome-extension"),
                Some("crx"),
                "GoogleChromeExtension",
            ),
            Self::Cursor => (
                "Windows cursor",
                Some("image/x-icon"),
                Some("cur"),
                "Cursor",
            ),
            Self::Dds => (
                "DirectDraw surface",
                Some("image/vnd-ms.dds"),
                Some("dds"),
                "Dds",
            ),
            Self::Deb => (
                "Debian package",
                Some("application/vnd.debian.binary-package"),
                Some("deb"),
                "Deb",
            ),
            Self::Dalvik => (
                "Dalvik",
                Some("application/vnd.android.dex"),
                Some("dex"),
                "Dalvik",
            ),
            Self::Djvu => ("DjVu", Some("image/vnd.djvu"), Some("djvu"), "Djvu"),
            Self::AppleDiskImage => (
                "Apple disk image",
                Some("application/x-apple-diskimage"),
                Some("dmg"),
                "AppleDiskImage",
            ),
            Self::ELF => ("ELF", None, None, "ELF"),
            Self::MSDOS => (
                "DOS/PE executable",
                Some("application/vnd.microsoft.portable-executable"),
                Some("exe"),
                "MSDOS",
            ),
            Self::OpenExr => ("OpenEXR", Some("image/x-exr"), Some("exr"), "OpenExr"),
            Self::FbxBinary => ("FBX binary", None, Some("fbx"), "FbxBinary"),
            Self::Fits => ("FITS", Some("image/fits"), Some("fits"), "Fits"),
            Self::Flac => ("FLAC", Some("audio/flac"), Some("flac"), "Flac"),
            Self::FlashVideo => (
                "Flash video",
                Some("video/x-flv"),
                Some("flv"),
                "FlashVideo",
            ),
            Self::Gguf => ("GGUF", None, Some("gguf"), "Gguf"),
            Self::GIF => ("GIF", Some("image/gif"), Some("gif"), "GIF"),
            Self::GltfBinary => (
                "glTF binary",
                Some("model/gltf-binary"),
                Some("glb"),
                "GltfBinary",
            ),
            Self::Gzip => ("Gzip", Some("application/gzip"), Some("gz"), "Gzip"),
            Self::Hdf5 => ("HDF5", Some("application/x-hdf5"), Some("h5"), "Hdf5"),
            Self::NoodlesoftHazel => ("Noodlesoft Hazel", None, None, "NoodlesoftHazel"),
            Self::Radiance => (
                "Radiance HDR",
                Some("image/vnd.radiance"),
                Some("hdr"),
                "Radiance",
            ),
            Self::AppleIconImage => (
                "Apple icon",
                Some("image/icns"),
                Some("icns"),
                "AppleIconImage",
            ),
            Self::ICO => ("Windows icon", Some("image/x-icon"), Some("ico"), "ICO"),
            Self::ISO => (
                "ISO 9660",
                Some("application/x-iso9660-image"),
                Some("iso"),
                "ISO",
            ),
            Self::OpenGLIrisPerformer => {
                ("OpenGL Iris Performer", None, None, "OpenGLIrisPerformer")
            }
            Self::JPEG2000 => ("JPEG 2000", Some("image/jp2"), Some("jp2"), "JPEG2000"),
            Self::Jpg => ("JPEG", Some("image/jpeg"), Some("jpg"), "Jpg"),
            Self::JpegXl => ("JPEG XL", Some("image/jxl"), Some("jxl"), "JpegXl"),
            Self::Ktx => ("KTX 1", Some("image/ktx"), Some("ktx"), "Ktx"),
            Self::Ktx2 => ("KTX 2", Some("image/ktx2"), Some("ktx2"), "Ktx2"),
            Self::WindowsShortcut => (
                "Windows shortcut",
                Some("application/x-ms-shortcut"),
                Some("lnk"),
                "WindowsShortcut",
            ),
            Self::Lua => (
                "Lua byte code",
                Some("application/x-lua-bytecode"),
                Some("luac"),
                "Lua",
            ),
            Self::Lz4 => ("LZ4 frame", Some("application/x-lz4"), Some("lz4"), "Lz4"),
            Self::Lzh => (
                "LHA/LZH",
                Some("application/x-lzh-compressed"),
                Some("lzh"),
                "Lzh",
            ),
            Self::MachO => ("Mach-O", None, None, "MachO"),
            Self::Matlab => (
                "MATLAB",
                Some("application/x-matlab-data"),
                Some("mat"),
                "Matlab",
            ),
            Self::Midi => ("MIDI", Some("audio/midi"), Some("mid"), "Midi"),
            Self::MatroskaMediaContainer => (
                "Matroska",
                Some("video/x-matroska"),
                Some("mkv"),
                "MatroskaMediaContainer",
            ),
            Self::Mobipocket => (
                "Mobipocket",
                Some("application/x-mobipocket-ebook"),
                Some("mobi"),
                "Mobipocket",
            ),
            Self::ModuleForEvenvironmentModules => (
                "Environment module",
                None,
                None,
                "ModuleForEvenvironmentModules",
            ),
            Self::MP3 => ("MP3", Some("audio/mpeg"), Some("mp3"), "MP3"),
            Self::IsoMedia => ("ISO base media", Some("video/mp4"), Some("mp4"), "IsoMedia"),
            Self::MpegProgramStream => (
                "MPEG program stream",
                Some("video/mpeg"),
                Some("mpg"),
                "MpegProgramStream",
            ),
            Self::Numpy => ("NumPy .npy", None, Some("npy"), "Numpy"),
            Self::OGG => ("Ogg", Some("audio/ogg"), Some("ogg"), "OGG"),
            Self::OleCompoundFile => ("OLE compound file", None, None, "OleCompoundFile"),
            Self::Orc => (
                "Apache ORC",
                Some("application/vnd.apache.orc"),
                Some("orc"),
                "Orc",
            ),
            Self::OpenTypeFont => (
                "OpenType font",
                Some("font/otf"),
                Some("otf"),
                "OpenTypeFont",
            ),
            Self::Par2 => ("PAR2", Some("application/x-par2"), Some("par2"), "Par2"),
            Self::Parquet => (
                "Parquet",
                Some("application/vnd.apache.parquet"),
                Some("parquet"),
                "Parquet",
            ),
            Self::Pcap => (
                "pcap",
                Some("application/vnd.tcpdump.pcap"),
                Some("pcap"),
                "Pcap",
            ),
            Self::PcapNg => (
                "pcapng",
                Some("application/x-pcapng"),
                Some("pcapng"),
                "PcapNg",
            ),
            Self::PhotoCapTemplate => ("PhotoCap template", None, Some("pct"), "PhotoCapTemplate"),
            Self::Pcx => ("PCX", Some("image/x-pcx"), Some("pcx"), "Pcx"),
            Self::PDF => ("PDF", Some("application/pdf"), Some("pdf"), "PDF"),
            Self::Pickle => ("Python pickle", None, None, "Pickle"),
            Self::Ply => ("Stanford PLY", Some("text/x-ply"), Some("ply"), "Ply"),
            Self::Png => ("PNG", Some("image/png"), Some("png"), "Png"),
            Self::PostScript => (
                "PostScript",
                Some("application/postscript"),
                Some("ps"),
                "PostScript",
            ),
            Self::_8BPS => (
                "Photoshop PSD",
                Some("image/vnd.adobe.photoshop"),
                Some("psd"),
                "_8BPS",
            ),
            Self::Qcow => (
                "QCOW",
                Some("application/x-qemu-qcow"),
                Some("qcow"),
                "Qcow",
            ),
            Self::Qcow2 => (
                "QCOW2",
                Some("application/x-qemu-qcow"),
                Some("qcow2"),
                "Qcow2",
            ),
            Self::RAR => ("RAR", Some("application/vnd.rar"), Some("rar"), "RAR"),
            Self::RData => (
                "R serialized data",
                Some("application/x-r-data"),
                Some("rdata"),
                "RData",
            ),
            Self::RPM => ("RPM", Some("application/x-rpm"), Some("rpm"), "RPM"),
            Self::RichTextFormat => (
                "Rich Text Format",
                Some("application/rtf"),
                Some("rtf"),
                "RichTextFormat",
            ),
            Self::ScriptExecute => ("Script / shebang", None, None, "ScriptExecute"),
            Self::SerializedJavaData => ("Java serialization", None, None, "SerializedJavaData"),
            Self::StuffitSit => (
                "StuffIt .sit",
                Some("application/x-stuffit"),
                Some("sit"),
                "StuffitSit",
            ),
            Self::Slob => ("StarDict binary", None, Some("slob"), "Slob"),
            Self::SQLite => (
                "SQLite",
                Some("application/vnd.sqlite3"),
                Some("sqlite"),
                "SQLite",
            ),
            Self::Stuffit => (
                "StuffIt",
                Some("application/x-stuffit"),
                Some("sit"),
                "Stuffit",
            ),
            Self::Swf => (
                "SWF",
                Some("application/x-shockwave-flash"),
                Some("swf"),
                "Swf",
            ),
            Self::Tar => ("Tar", Some("application/x-tar"), Some("tar"), "Tar"),
            Self::Tiff => ("TIFF / BigTIFF", Some("image/tiff"), Some("tiff"), "Tiff"),
            Self::BitTorrent => (
                "BitTorrent metainfo",
                Some("application/x-bittorrent"),
                Some("torrent"),
                "BitTorrent",
            ),
            Self::FontCollection => (
                "Font collection",
                Some("font/collection"),
                Some("ttc"),
                "FontCollection",
            ),
            Self::TrueTypeFont => (
                "TrueType font",
                Some("font/ttf"),
                Some("ttf"),
                "TrueTypeFont",
            ),
            Self::VBScriptEncoded => (
                "Encoded VBScript",
                Some("text/x-vbscript"),
                Some("vbe"),
                "VBScriptEncoded",
            ),
            Self::VirtualBoxVdi => (
                "VirtualBox VDI",
                Some("application/x-vdi"),
                Some("vdi"),
                "VirtualBoxVdi",
            ),
            Self::VirtualHd => (
                "Virtual HD",
                Some("application/x-vhd"),
                Some("vhd"),
                "VirtualHd",
            ),
            Self::Vmdk => (
                "VMware disk image",
                Some("application/x-vmdk"),
                Some("vmdk"),
                "Vmdk",
            ),
            Self::CreativeVoiceFile => (
                "Creative Voice File",
                Some("audio/x-voc"),
                Some("voc"),
                "CreativeVoiceFile",
            ),
            Self::DoomWad => (
                "Doom WAD",
                Some("application/x-doom-wad"),
                Some("wad"),
                "DoomWad",
            ),
            Self::WASM => (
                "WebAssembly",
                Some("application/wasm"),
                Some("wasm"),
                "WASM",
            ),
            Self::WEBP => ("WebP", Some("image/webp"), Some("webp"), "WEBP"),
            Self::WindowImagingFormat => (
                "Windows Imaging Format",
                Some("application/x-ms-wim"),
                Some("wim"),
                "WindowImagingFormat",
            ),
            Self::Woff => ("WOFF", Some("font/woff"), Some("woff"), "Woff"),
            Self::Woff2 => ("WOFF2", Some("font/woff2"), Some("woff2"), "Woff2"),
            Self::WavPack => ("WavPack", Some("audio/x-wavpack"), Some("wv"), "WavPack"),
            Self::GimpXcf => ("GIMP XCF", Some("image/x-xcf"), Some("xcf"), "GimpXcf"),
            Self::XML => ("XML", Some("application/xml"), Some("xml"), "XML"),
            Self::Xz => ("XZ", Some("application/x-xz"), Some("xz"), "Xz"),
            Self::PkgZip => (
                "Zip / JAR / APK",
                Some("application/zip"),
                Some("zip"),
                "PkgZip",
            ),
            Self::Zlib => ("zlib stream", None, None, "Zlib"),
            Self::Zstd => ("Zstandard", Some("application/zstd"), Some("zst"), "Zstd"),
        }
    }

    /// The name this format is written with in documentation and in a `file`
    /// listing, such as `"PNG"` or `"Zip / JAR / APK"`.
    ///
    /// `const` because the answer is a literal in the generated body, and a caller
    /// building a table of labels at compile time should not have to give that up.
    #[must_use]
    #[inline]
    pub const fn display_name(self) -> &'static str {
        self.meta().0
    }

    /// The registered MIME type, or [`None`] when there is none.
    ///
    /// [`None`] means "not registered or not verified", never "unknown". A caller
    /// that needs an answer should fall back to `application/octet-stream` itself,
    /// so the choice stays visible at the call site rather than baked in here.
    #[must_use]
    #[inline]
    pub const fn mime(self) -> Option<&'static str> {
        self.meta().1
    }

    /// The conventional file extension, or [`None`] when there is none.
    ///
    /// Without a leading dot, and advisory: detection never reads a file name, so a
    /// `.jpg` holding a PNG is reported as a PNG. The extension is for choosing
    /// what to *write*, which is the one question a magic number cannot answer.
    #[must_use]
    #[inline]
    pub const fn extension(self) -> Option<&'static str> {
        self.meta().2
    }

    /// The name of the enum variant, which is what `format!("{:?}")` prints.
    ///
    /// Its own method because the two names answer different questions and are not
    /// interchangeable: this one is `Png` and [`Self::display_name`] is `"PNG"`,
    /// and a caller that wants a stable identifier wants this one.
    #[must_use]
    #[inline]
    pub const fn variant_name(self) -> &'static str {
        self.meta().3
    }

    /// The format whose [`Self::variant_name`] is `name`, or [`None`].
    ///
    /// Exact and case-sensitive, and that is the point: `Png`, `png` and `PNG` are
    /// three spellings and only one is the identifier this crate uses. A loose
    /// lookup belongs in whatever parses a command line, where forgiving is right,
    /// rather than in the library, where a wrong answer is silent.
    ///
    /// ```rust
    /// use magical_rs::magical::magic::FileKind;
    ///
    /// assert_eq!(FileKind::from_name("Png"), Some(FileKind::Png));
    /// assert_eq!(FileKind::from_name("png"), None);
    /// assert_eq!(FileKind::from_name("Nonsense"), None);
    /// ```
    #[must_use]
    #[inline]
    // A hundred and fourteen arms, for the reason the meta match gives. Unlike
    // that one this could have been a table, but a match on a string compiles
    // to a length switch and a memcmp rather than a scan over an array.
    #[allow(clippy::too_many_lines)]
    pub fn from_name(name: &str) -> Option<Self> {
        match name {
            "SevenZip" => Some(Self::SevenZip),
            "AceCompressed" => Some(Self::AceCompressed),
            "Aiff" => Some(Self::Aiff),
            "Amr" => Some(Self::Amr),
            "MonkeyAudio" => Some(Self::MonkeyAudio),
            "Arj" => Some(Self::Arj),
            "Asf" => Some(Self::Asf),
            "AuAudioFileFormat" => Some(Self::AuAudioFileFormat),
            "Avro" => Some(Self::Avro),
            "BLENDER" => Some(Self::BLENDER),
            "Bitmap" => Some(Self::Bitmap),
            "BinaryPlist" => Some(Self::BinaryPlist),
            "Bzip" => Some(Self::Bzip),
            "Cabinet" => Some(Self::Cabinet),
            "CoreAudio" => Some(Self::CoreAudio),
            "Chm" => Some(Self::Chm),
            "Class" => Some(Self::Class),
            "Cpio" => Some(Self::Cpio),
            "GoogleChromeExtension" => Some(Self::GoogleChromeExtension),
            "Cursor" => Some(Self::Cursor),
            "Dds" => Some(Self::Dds),
            "Deb" => Some(Self::Deb),
            "Dalvik" => Some(Self::Dalvik),
            "Djvu" => Some(Self::Djvu),
            "AppleDiskImage" => Some(Self::AppleDiskImage),
            "ELF" => Some(Self::ELF),
            "MSDOS" => Some(Self::MSDOS),
            "OpenExr" => Some(Self::OpenExr),
            "FbxBinary" => Some(Self::FbxBinary),
            "Fits" => Some(Self::Fits),
            "Flac" => Some(Self::Flac),
            "FlashVideo" => Some(Self::FlashVideo),
            "Gguf" => Some(Self::Gguf),
            "GIF" => Some(Self::GIF),
            "GltfBinary" => Some(Self::GltfBinary),
            "Gzip" => Some(Self::Gzip),
            "Hdf5" => Some(Self::Hdf5),
            "NoodlesoftHazel" => Some(Self::NoodlesoftHazel),
            "Radiance" => Some(Self::Radiance),
            "AppleIconImage" => Some(Self::AppleIconImage),
            "ICO" => Some(Self::ICO),
            "ISO" => Some(Self::ISO),
            "OpenGLIrisPerformer" => Some(Self::OpenGLIrisPerformer),
            "JPEG2000" => Some(Self::JPEG2000),
            "Jpg" => Some(Self::Jpg),
            "JpegXl" => Some(Self::JpegXl),
            "Ktx" => Some(Self::Ktx),
            "Ktx2" => Some(Self::Ktx2),
            "WindowsShortcut" => Some(Self::WindowsShortcut),
            "Lua" => Some(Self::Lua),
            "Lz4" => Some(Self::Lz4),
            "Lzh" => Some(Self::Lzh),
            "MachO" => Some(Self::MachO),
            "Matlab" => Some(Self::Matlab),
            "Midi" => Some(Self::Midi),
            "MatroskaMediaContainer" => Some(Self::MatroskaMediaContainer),
            "Mobipocket" => Some(Self::Mobipocket),
            "ModuleForEvenvironmentModules" => Some(Self::ModuleForEvenvironmentModules),
            "MP3" => Some(Self::MP3),
            "IsoMedia" => Some(Self::IsoMedia),
            "MpegProgramStream" => Some(Self::MpegProgramStream),
            "Numpy" => Some(Self::Numpy),
            "OGG" => Some(Self::OGG),
            "OleCompoundFile" => Some(Self::OleCompoundFile),
            "Orc" => Some(Self::Orc),
            "OpenTypeFont" => Some(Self::OpenTypeFont),
            "Par2" => Some(Self::Par2),
            "Parquet" => Some(Self::Parquet),
            "Pcap" => Some(Self::Pcap),
            "PcapNg" => Some(Self::PcapNg),
            "PhotoCapTemplate" => Some(Self::PhotoCapTemplate),
            "Pcx" => Some(Self::Pcx),
            "PDF" => Some(Self::PDF),
            "Pickle" => Some(Self::Pickle),
            "Ply" => Some(Self::Ply),
            "Png" => Some(Self::Png),
            "PostScript" => Some(Self::PostScript),
            "_8BPS" => Some(Self::_8BPS),
            "Qcow" => Some(Self::Qcow),
            "Qcow2" => Some(Self::Qcow2),
            "RAR" => Some(Self::RAR),
            "RData" => Some(Self::RData),
            "RPM" => Some(Self::RPM),
            "RichTextFormat" => Some(Self::RichTextFormat),
            "ScriptExecute" => Some(Self::ScriptExecute),
            "SerializedJavaData" => Some(Self::SerializedJavaData),
            "StuffitSit" => Some(Self::StuffitSit),
            "Slob" => Some(Self::Slob),
            "SQLite" => Some(Self::SQLite),
            "Stuffit" => Some(Self::Stuffit),
            "Swf" => Some(Self::Swf),
            "Tar" => Some(Self::Tar),
            "Tiff" => Some(Self::Tiff),
            "BitTorrent" => Some(Self::BitTorrent),
            "FontCollection" => Some(Self::FontCollection),
            "TrueTypeFont" => Some(Self::TrueTypeFont),
            "VBScriptEncoded" => Some(Self::VBScriptEncoded),
            "VirtualBoxVdi" => Some(Self::VirtualBoxVdi),
            "VirtualHd" => Some(Self::VirtualHd),
            "Vmdk" => Some(Self::Vmdk),
            "CreativeVoiceFile" => Some(Self::CreativeVoiceFile),
            "DoomWad" => Some(Self::DoomWad),
            "WASM" => Some(Self::WASM),
            "WEBP" => Some(Self::WEBP),
            "WindowImagingFormat" => Some(Self::WindowImagingFormat),
            "Woff" => Some(Self::Woff),
            "Woff2" => Some(Self::Woff2),
            "WavPack" => Some(Self::WavPack),
            "GimpXcf" => Some(Self::GimpXcf),
            "XML" => Some(Self::XML),
            "Xz" => Some(Self::Xz),
            "PkgZip" => Some(Self::PkgZip),
            "Zlib" => Some(Self::Zlib),
            "Zstd" => Some(Self::Zstd),
            _ => None,
        }
    }
}
