#!/usr/bin/perl

use strict;
use warnings;
use File::Find;

sub walk_dirs {
    my $file = $File::Find::name;

}

sub checks_py {
    return unless -f $_;
    return unless /\.py$/i;

    my $filename = $_;

    if ($filename =~ /[A-Z]/) {
        print "[ERROR] File with uppercase name is NOT allowed: $filename\n";
        exit 1;
    }

    print "[OK]: $filename\n"
}

find(\&checks_py, "venus_gui");