// Generated by scripts/gen_formats.mjs from formats.json. Do not edit;
// run `npm run gen`.
//
// The indices and the order come from `abi_order`, which is the position of each
// variant in `pub enum FileKind` in crates/magical_rs. That order *is* the ABI: a
// file kind crosses the wasm boundary as its Rust discriminant, so entry N here is
// what the compiled module reports as N, and nothing at runtime would notice if it
// drifted. test/kinds.test.js compares every name against the kind indices the
// compiled module reports.
//
// The names, MIME types and extensions come from the same table the Rust and Python
// metadata are generated from, so a MIME type cannot be one thing in Rust and
// another in JavaScript.
//
// The types live in the .d.ts beside this file, not here: `as const` and
// `export type` are TypeScript syntax and would not parse in the .js Node loads. A
// single .ts file would mean a build step, and this package ships no build.

/** Every format the built-in detection table can return, in the crate's own order. */
export declare const FileKind: {
  readonly [K in FileKind]: K
}

/** The name of a format, as a TypeScript type. */
export type FileKind =
  | "Png"
  | "Bitmap"
  | "Gzip"
  | "Bzip"
  | "PkgZip"
  | "Tar"
  | "MSDOS"
  | "Jpg"
  | "Class"
  | "MP3"
  | "ISO"
  | "RPM"
  | "SQLite"
  | "XML"
  | "ICO"
  | "WASM"
  | "Deb"
  | "RAR"
  | "ScriptExecute"
  | "ELF"
  | "OGG"
  | "_8BPS"
  | "BLENDER"
  | "TrueTypeFont"
  | "OpenTypeFont"
  | "ModuleForEvenvironmentModules"
  | "WindowImagingFormat"
  | "Slob"
  | "SerializedJavaData"
  | "CreativeVoiceFile"
  | "AuAudioFileFormat"
  | "OpenGLIrisPerformer"
  | "NoodlesoftHazel"
  | "VBScriptEncoded"
  | "WEBP"
  | "AppleIconImage"
  | "GIF"
  | "JPEG2000"
  | "PDF"
  | "AppleDiskImage"
  | "Cabinet"
  | "MatroskaMediaContainer"
  | "RichTextFormat"
  | "PhotoCapTemplate"
  | "AceCompressed"
  | "FlashVideo"
  | "Vmdk"
  | "GoogleChromeExtension"
  | "SevenZip"
  | "Xz"
  | "Lz4"
  | "Zstd"
  | "Lzh"
  | "Cpio"
  | "Arj"
  | "Stuffit"
  | "StuffitSit"
  | "Par2"
  | "Zlib"
  | "Tiff"
  | "Pcx"
  | "Dds"
  | "Ktx"
  | "Ktx2"
  | "OpenExr"
  | "Radiance"
  | "JpegXl"
  | "Cursor"
  | "GimpXcf"
  | "Fits"
  | "Midi"
  | "Aiff"
  | "Flac"
  | "WavPack"
  | "CoreAudio"
  | "Amr"
  | "MonkeyAudio"
  | "IsoMedia"
  | "Swf"
  | "Asf"
  | "MpegProgramStream"
  | "PostScript"
  | "Djvu"
  | "Mobipocket"
  | "Chm"
  | "OleCompoundFile"
  | "MachO"
  | "Dalvik"
  | "Lua"
  | "WindowsShortcut"
  | "Woff"
  | "Woff2"
  | "FontCollection"
  | "Numpy"
  | "Hdf5"
  | "Matlab"
  | "Parquet"
  | "Orc"
  | "Avro"
  | "BinaryPlist"
  | "Pickle"
  | "Gguf"
  | "RData"
  | "GltfBinary"
  | "FbxBinary"
  | "Ply"
  | "DoomWad"
  | "Qcow"
  | "Qcow2"
  | "VirtualBoxVdi"
  | "VirtualHd"
  | "Pcap"
  | "PcapNg"
  | "BitTorrent"

/**
 * Name to Rust discriminant, in the order the crate declares them.
 *
 * Exported because it is what turns a name into a call. The wasm side answers in
 * discriminants because that is all it can pass; this is where a name becomes
 * one.
 */
export declare const FILE_KIND_INDICES: ReadonlyMap<FileKind, number>

/**
 * Rust discriminant to name, indexed by that discriminant.
 *
 * The other direction, and the one the introspection API needs: the table arrives
 * from wasm as 114 anonymous integers, and each has to become a name. An array
 * rather than a reversed Map because this is read once per entry at import and
 * then never again.
 */
export declare const FILE_KIND_NAMES: readonly FileKind[]

/** The display name of a format, such as `PNG` or `Zip / JAR / APK`. */
export declare const FILE_KIND_DISPLAY_NAME: {
  readonly [K in FileKind]: string
}

/**
 * The registered MIME type of a format, or `null` where there is none.
 *
 * `null` means "not registered or not verified", never "unknown".
 */
export declare const FILE_KIND_MIME: {
  readonly [K in FileKind]: string | null
}

/**
 * The conventional extension of a format, or `null` where there is none.
 *
 * No leading dot, and advisory: detection never reads a file name.
 */
export declare const FILE_KIND_EXTENSION: {
  readonly [K in FileKind]: string | null
}
