"""The :class:`FileKind` enum, one member per detectable file format,

and the :class:`Signature` that describes how each one is detected.

Generated by ``scripts/gen_kinds.ps1``. Do not edit by hand.

``Signature`` lives here rather than in ``_signatures`` because the two are
mutually recursive: a ``Signature`` names a ``FileKind``, and a ``FileKind``
has a ``rule`` that is a ``Signature``. Keeping them in one module is what
avoids an import cycle, and the alternative was a deferred import that a type
checker flags anyway. ``_signatures`` holds the functions that walk the
table and imports from here.
"""

from __future__ import annotations

import dataclasses
from enum import Enum
from typing import Final

from ._magical_rs import kind_matches, signature_of

__all__ = ["FileKind", "Signature"]

# The row the extension returns is spelled out at each unpacking site rather
# than aliased. A quoted module-level alias would be the obvious way to keep
# the two sites in step, but pyright does not accept a string as a type
# alias, and `typing.TypeAlias` is 3.10 while this package supports 3.8.
# `tests/test_stub.py` pins the extension against the stub, which is where
# the shape is actually asserted.


@dataclasses.dataclass(frozen=True)
class Signature:
    """One entry of the built-in detection table.

    Frozen because the table is a ``static`` in Rust and nothing here can
    change it: a caller that wants a different answer wants a level 2 rule,
    which is what :class:`~magical_py.MagicCustom` is for.
    """

    kind: FileKind
    signatures: tuple[bytes, ...]
    offsets: tuple[int, ...]
    max_bytes_read: int
    uses_predicate: bool

    @property
    def max_offset(self) -> int:
        """The furthest byte position this entry compares at.

        Zero for a predicate entry, whose rule decides on the buffer as a
        whole rather than at a position.
        """
        return max(self.offsets, default=0)

    def matches(self, data: bytes) -> bool:
        """Report whether *this* format's rule matches, ignoring the table.

        The one thing :func:`magical_py.detect` cannot tell you. Detection
        stops at the first entry that matched, so a format whose magic is
        also another format's is unreachable through it. A KTX2 file answers
        :func:`~magical_py.detect_bytes` with ``FileKind.Ktx2`` and this with
        ``True`` for ``FileKind.Ktx``, whose three magic bytes are a prefix
        of KTX2's.

        :param data: The leading bytes of a file.
        :returns: Whether this format's own rule would match them.
        """
        return kind_matches(self.kind.name, data)

    @classmethod
    def _from_row(cls, row: tuple[str, list[bytes], list[int], int, bool]) -> Signature:
        kind, signatures, offsets, max_bytes_read, uses_predicate = row
        return cls(
            kind=FileKind[kind],
            signatures=tuple(signatures),
            offsets=tuple(offsets),
            max_bytes_read=max_bytes_read,
            uses_predicate=uses_predicate,
        )


class FileKind(Enum):
    """A file format that ``magical_rs`` can detect.

    Members are named after the Rust ``FileKind`` variants, so a name that
    appears in the ``magical_rs`` documentation appears here too. The
    :attr:`value` of each member is a short, stable identifier intended for
    serialisation; use :attr:`mime` when you need a media type.

    Detect a format with :func:`magical_py.detect` or
    :func:`magical_py.detect_bytes`.
    """

    @classmethod
    def from_value(cls, value: str) -> FileKind:
        """Look a member up by its serialised value.

        :param value: A member :attr:`value`, such as ``"png"``.
        :returns: The matching member.
        :raises ValueError: If no member has that value.
        """
        return cls(value)

    @property
    def description(self) -> str:
        """A human-readable name for the format, such as ``"PNG"``."""
        return _META[self.name][0]

    @property
    def mime(self) -> str | None:
        """The registered media type, or ``None`` if there is none.

        ``None`` means no media type is registered or verified for this
        format. It never means "unknown", which would be a guess.
        """
        return _META[self.name][1]

    @property
    def extension(self) -> str | None:
        """The conventional file extension, or ``None`` if there is none.

        The extension carries no leading dot. It is advisory: detection
        never looks at the file name.
        """
        return _META[self.name][2]

    @property
    def rule(self) -> Signature:
        """The table entry that detects this format.

        What the format is matched on: the bytes, the offsets they are
        compared at, and the read size the entry declares. A format
        decided by a function rather than a fixed pattern reports
        ``uses_predicate`` and no signatures.

        :raises ValueError: If no signature produces this format, which
            would mean the enum and the table had drifted apart.
        """
        entry = signature_of(self.name)
        if entry is None:
            raise ValueError(
                f"{self.name} is not a format the detection table produces"
            )
        return Signature._from_row(entry)

    def matches(self, data: bytes) -> bool:
        """Report whether this format's own rule matches ``data``.

        :func:`magical_py.detect` stops at the first table entry that
        matched, so a format whose magic is also another format's is
        unreachable through it. This asks only about this one.

        :param data: The leading bytes of a file.
        :returns: Whether this format's own rule would match them.
        """
        return kind_matches(self.name, data)

    _8BPS = 'psd'
    """Photoshop PSD."""

    AceCompressed = 'ace'
    """ACE archive."""

    Aiff = 'aiff'
    """AIFF."""

    Amr = 'amr'
    """AMR audio."""

    AppleDiskImage = 'dmg'
    """Apple disk image."""

    AppleIconImage = 'icns'
    """Apple icon."""

    Arj = 'arj'
    """ARJ."""

    Asf = 'asf'
    """ASF / WMV."""

    AuAudioFileFormat = 'au'
    """AU audio."""

    Avro = 'avro'
    """Avro."""

    BinaryPlist = 'bplist'
    """Binary plist."""

    Bitmap = 'bmp'
    """Bitmap."""

    BitTorrent = 'torrent'
    """BitTorrent metainfo."""

    BLENDER = 'blend'
    """Blender."""

    Bzip = 'bz2'
    """Bzip2."""

    Cabinet = 'cab'
    """Cabinet."""

    Chm = 'chm'
    """MS Compiled HTML."""

    Class = 'class'
    """Java class."""

    CoreAudio = 'caf'
    """Core Audio."""

    Cpio = 'cpio'
    """cpio."""

    CreativeVoiceFile = 'voc'
    """Creative Voice File."""

    Cursor = 'cur'
    """Windows cursor."""

    Dalvik = 'dex'
    """Dalvik."""

    Dds = 'dds'
    """DirectDraw surface."""

    Deb = 'deb'
    """Debian package."""

    Djvu = 'djvu'
    """DjVu."""

    DoomWad = 'wad'
    """Doom WAD."""

    ELF = 'elf'
    """ELF."""

    FbxBinary = 'fbx'
    """FBX binary."""

    Fits = 'fits'
    """FITS."""

    Flac = 'flac'
    """FLAC."""

    FlashVideo = 'flv'
    """Flash video."""

    FontCollection = 'ttc'
    """Font collection."""

    Gguf = 'gguf'
    """GGUF."""

    GIF = 'gif'
    """GIF."""

    GimpXcf = 'xcf'
    """GIMP XCF."""

    GltfBinary = 'glb'
    """glTF binary."""

    GoogleChromeExtension = 'crx'
    """Chrome extension."""

    Gzip = 'gz'
    """Gzip."""

    Hdf5 = 'h5'
    """HDF5."""

    ICO = 'ico'
    """Windows icon."""

    ISO = 'iso'
    """ISO 9660."""

    IsoMedia = 'mp4'
    """ISO base media."""

    JPEG2000 = 'jp2'
    """JPEG 2000."""

    JpegXl = 'jxl'
    """JPEG XL."""

    Jpg = 'jpg'
    """JPEG."""

    Ktx = 'ktx'
    """KTX 1."""

    Ktx2 = 'ktx2'
    """KTX 2."""

    Lua = 'luac'
    """Lua byte code."""

    Lz4 = 'lz4'
    """LZ4 frame."""

    Lzh = 'lzh'
    """LHA/LZH."""

    MachO = 'macho'
    """Mach-O."""

    Matlab = 'mat'
    """MATLAB."""

    MatroskaMediaContainer = 'mkv'
    """Matroska."""

    Midi = 'mid'
    """MIDI."""

    Mobipocket = 'mobi'
    """Mobipocket."""

    ModuleForEvenvironmentModules = 'module'
    """Environment module."""

    MonkeyAudio = 'ape'
    """Monkey\'s Audio."""

    MP3 = 'mp3'
    """MP3."""

    MpegProgramStream = 'mpg'
    """MPEG program stream."""

    MSDOS = 'exe'
    """DOS/PE executable."""

    NoodlesoftHazel = 'hazel'
    """Noodlesoft Hazel."""

    Numpy = 'npy'
    """NumPy .npy."""

    OGG = 'ogg'
    """Ogg."""

    OleCompoundFile = 'ole'
    """OLE compound file."""

    OpenExr = 'exr'
    """OpenEXR."""

    OpenGLIrisPerformer = 'iv'
    """OpenGL Iris Performer."""

    OpenTypeFont = 'otf'
    """OpenType font."""

    Orc = 'orc'
    """Apache ORC."""

    Par2 = 'par2'
    """PAR2."""

    Parquet = 'parquet'
    """Parquet."""

    Pcap = 'pcap'
    """pcap."""

    PcapNg = 'pcapng'
    """pcapng."""

    Pcx = 'pcx'
    """PCX."""

    PDF = 'pdf'
    """PDF."""

    PhotoCapTemplate = 'pct'
    """PhotoCap template."""

    Pickle = 'pickle'
    """Python pickle."""

    PkgZip = 'zip'
    """Zip / JAR / APK."""

    Ply = 'ply'
    """Stanford PLY."""

    Png = 'png'
    """PNG."""

    PostScript = 'ps'
    """PostScript."""

    Qcow = 'qcow'
    """QCOW."""

    Qcow2 = 'qcow2'
    """QCOW2."""

    Radiance = 'hdr'
    """Radiance HDR."""

    RAR = 'rar'
    """RAR."""

    RData = 'rdata'
    """R serialized data."""

    RichTextFormat = 'rtf'
    """Rich Text Format."""

    RPM = 'rpm'
    """RPM."""

    ScriptExecute = 'script'
    """Script / shebang."""

    SerializedJavaData = 'ser'
    """Java serialization."""

    SevenZip = '7z'
    """7-Zip."""

    Slob = 'slob'
    """StarDict binary."""

    SQLite = 'sqlite'
    """SQLite."""

    Stuffit = 'stuffit'
    """StuffIt."""

    StuffitSit = 'sit'
    """StuffIt .sit."""

    Swf = 'swf'
    """SWF."""

    Tar = 'tar'
    """Tar."""

    Tiff = 'tiff'
    """TIFF / BigTIFF."""

    TrueTypeFont = 'ttf'
    """TrueType font."""

    VBScriptEncoded = 'vbe'
    """Encoded VBScript."""

    VirtualBoxVdi = 'vdi'
    """VirtualBox VDI."""

    VirtualHd = 'vhd'
    """Virtual HD."""

    Vmdk = 'vmdk'
    """VMware disk image."""

    WASM = 'wasm'
    """WebAssembly."""

    WavPack = 'wv'
    """WavPack."""

    WEBP = 'webp'
    """WebP."""

    WindowImagingFormat = 'wim'
    """Windows Imaging Format."""

    WindowsShortcut = 'lnk'
    """Windows shortcut."""

    Woff = 'woff'
    """WOFF."""

    Woff2 = 'woff2'
    """WOFF2."""

    XML = 'xml'
    """XML."""

    Xz = 'xz'
    """XZ."""

    Zlib = 'zlib'
    """zlib stream."""

    Zstd = 'zst'
    """Zstandard."""


#: member name -> (description, mime, extension)
_META: Final[dict[str, tuple[str, str | None, str | None]]] = {
    '_8BPS': ('Photoshop PSD', 'image/vnd.adobe.photoshop', 'psd'),
    'AceCompressed': ('ACE archive', None, None),
    'Aiff': ('AIFF', 'audio/aiff', 'aiff'),
    'Amr': ('AMR audio', 'audio/amr', 'amr'),
    'AppleDiskImage': ('Apple disk image', 'application/x-apple-diskimage', 'dmg'),
    'AppleIconImage': ('Apple icon', 'image/icns', 'icns'),
    'Arj': ('ARJ', 'application/x-arj', 'arj'),
    'Asf': ('ASF / WMV', 'video/x-ms-asf', 'asf'),
    'AuAudioFileFormat': ('AU audio', 'audio/basic', 'au'),
    'Avro': ('Avro', 'application/avro', 'avro'),
    'BinaryPlist': ('Binary plist', 'application/x-bplist', 'bplist'),
    'Bitmap': ('Bitmap', 'image/bmp', 'bmp'),
    'BitTorrent': ('BitTorrent metainfo', 'application/x-bittorrent', 'torrent'),
    'BLENDER': ('Blender', 'application/x-blender', 'blend'),
    'Bzip': ('Bzip2', 'application/x-bzip2', 'bz2'),
    'Cabinet': ('Cabinet', 'application/vnd.ms-cab-compressed', 'cab'),
    'Chm': ('MS Compiled HTML', 'application/vnd.ms-htmlhelp', 'chm'),
    'Class': ('Java class', 'application/java-vm', 'class'),
    'CoreAudio': ('Core Audio', 'audio/x-caf', 'caf'),
    'Cpio': ('cpio', 'application/x-cpio', 'cpio'),
    'CreativeVoiceFile': ('Creative Voice File', 'audio/x-voc', 'voc'),
    'Cursor': ('Windows cursor', 'image/x-icon', 'cur'),
    'Dalvik': ('Dalvik', 'application/vnd.android.dex', 'dex'),
    'Dds': ('DirectDraw surface', 'image/vnd-ms.dds', 'dds'),
    'Deb': ('Debian package', 'application/vnd.debian.binary-package', 'deb'),
    'Djvu': ('DjVu', 'image/vnd.djvu', 'djvu'),
    'DoomWad': ('Doom WAD', 'application/x-doom-wad', 'wad'),
    'ELF': ('ELF', None, None),
    'FbxBinary': ('FBX binary', None, 'fbx'),
    'Fits': ('FITS', 'image/fits', 'fits'),
    'Flac': ('FLAC', 'audio/flac', 'flac'),
    'FlashVideo': ('Flash video', 'video/x-flv', 'flv'),
    'FontCollection': ('Font collection', 'font/collection', 'ttc'),
    'Gguf': ('GGUF', None, 'gguf'),
    'GIF': ('GIF', 'image/gif', 'gif'),
    'GimpXcf': ('GIMP XCF', 'image/x-xcf', 'xcf'),
    'GltfBinary': ('glTF binary', 'model/gltf-binary', 'glb'),
    'GoogleChromeExtension': ('Chrome extension', 'application/x-chrome-extension', 'crx'),
    'Gzip': ('Gzip', 'application/gzip', 'gz'),
    'Hdf5': ('HDF5', 'application/x-hdf5', 'h5'),
    'ICO': ('Windows icon', 'image/x-icon', 'ico'),
    'ISO': ('ISO 9660', 'application/x-iso9660-image', 'iso'),
    'IsoMedia': ('ISO base media', 'video/mp4', 'mp4'),
    'JPEG2000': ('JPEG 2000', 'image/jp2', 'jp2'),
    'JpegXl': ('JPEG XL', 'image/jxl', 'jxl'),
    'Jpg': ('JPEG', 'image/jpeg', 'jpg'),
    'Ktx': ('KTX 1', 'image/ktx', 'ktx'),
    'Ktx2': ('KTX 2', 'image/ktx2', 'ktx2'),
    'Lua': ('Lua byte code', 'application/x-lua-bytecode', 'luac'),
    'Lz4': ('LZ4 frame', 'application/x-lz4', 'lz4'),
    'Lzh': ('LHA/LZH', 'application/x-lzh-compressed', 'lzh'),
    'MachO': ('Mach-O', None, None),
    'Matlab': ('MATLAB', 'application/x-matlab-data', 'mat'),
    'MatroskaMediaContainer': ('Matroska', 'video/x-matroska', 'mkv'),
    'Midi': ('MIDI', 'audio/midi', 'mid'),
    'Mobipocket': ('Mobipocket', 'application/x-mobipocket-ebook', 'mobi'),
    'ModuleForEvenvironmentModules': ('Environment module', None, None),
    'MonkeyAudio': ('Monkey\'s Audio', 'audio/x-monkeys-audio', 'ape'),
    'MP3': ('MP3', 'audio/mpeg', 'mp3'),
    'MpegProgramStream': ('MPEG program stream', 'video/mpeg', 'mpg'),
    'MSDOS': ('DOS/PE executable', 'application/vnd.microsoft.portable-executable', 'exe'),
    'NoodlesoftHazel': ('Noodlesoft Hazel', None, None),
    'Numpy': ('NumPy .npy', None, 'npy'),
    'OGG': ('Ogg', 'audio/ogg', 'ogg'),
    'OleCompoundFile': ('OLE compound file', None, None),
    'OpenExr': ('OpenEXR', 'image/x-exr', 'exr'),
    'OpenGLIrisPerformer': ('OpenGL Iris Performer', None, None),
    'OpenTypeFont': ('OpenType font', 'font/otf', 'otf'),
    'Orc': ('Apache ORC', 'application/vnd.apache.orc', 'orc'),
    'Par2': ('PAR2', 'application/x-par2', 'par2'),
    'Parquet': ('Parquet', 'application/vnd.apache.parquet', 'parquet'),
    'Pcap': ('pcap', 'application/vnd.tcpdump.pcap', 'pcap'),
    'PcapNg': ('pcapng', 'application/x-pcapng', 'pcapng'),
    'Pcx': ('PCX', 'image/x-pcx', 'pcx'),
    'PDF': ('PDF', 'application/pdf', 'pdf'),
    'PhotoCapTemplate': ('PhotoCap template', None, 'pct'),
    'Pickle': ('Python pickle', None, None),
    'PkgZip': ('Zip / JAR / APK', 'application/zip', 'zip'),
    'Ply': ('Stanford PLY', 'text/x-ply', 'ply'),
    'Png': ('PNG', 'image/png', 'png'),
    'PostScript': ('PostScript', 'application/postscript', 'ps'),
    'Qcow': ('QCOW', 'application/x-qemu-qcow', 'qcow'),
    'Qcow2': ('QCOW2', 'application/x-qemu-qcow', 'qcow2'),
    'Radiance': ('Radiance HDR', 'image/vnd.radiance', 'hdr'),
    'RAR': ('RAR', 'application/vnd.rar', 'rar'),
    'RData': ('R serialized data', 'application/x-r-data', 'rdata'),
    'RichTextFormat': ('Rich Text Format', 'application/rtf', 'rtf'),
    'RPM': ('RPM', 'application/x-rpm', 'rpm'),
    'ScriptExecute': ('Script / shebang', None, None),
    'SerializedJavaData': ('Java serialization', None, None),
    'SevenZip': ('7-Zip', 'application/x-7z-compressed', '7z'),
    'Slob': ('StarDict binary', None, 'slob'),
    'SQLite': ('SQLite', 'application/vnd.sqlite3', 'sqlite'),
    'Stuffit': ('StuffIt', 'application/x-stuffit', 'sit'),
    'StuffitSit': ('StuffIt .sit', 'application/x-stuffit', 'sit'),
    'Swf': ('SWF', 'application/x-shockwave-flash', 'swf'),
    'Tar': ('Tar', 'application/x-tar', 'tar'),
    'Tiff': ('TIFF / BigTIFF', 'image/tiff', 'tiff'),
    'TrueTypeFont': ('TrueType font', 'font/ttf', 'ttf'),
    'VBScriptEncoded': ('Encoded VBScript', 'text/x-vbscript', 'vbe'),
    'VirtualBoxVdi': ('VirtualBox VDI', 'application/x-vdi', 'vdi'),
    'VirtualHd': ('Virtual HD', 'application/x-vhd', 'vhd'),
    'Vmdk': ('VMware disk image', 'application/x-vmdk', 'vmdk'),
    'WASM': ('WebAssembly', 'application/wasm', 'wasm'),
    'WavPack': ('WavPack', 'audio/x-wavpack', 'wv'),
    'WEBP': ('WebP', 'image/webp', 'webp'),
    'WindowImagingFormat': ('Windows Imaging Format', 'application/x-ms-wim', 'wim'),
    'WindowsShortcut': ('Windows shortcut', 'application/x-ms-shortcut', 'lnk'),
    'Woff': ('WOFF', 'font/woff', 'woff'),
    'Woff2': ('WOFF2', 'font/woff2', 'woff2'),
    'XML': ('XML', 'application/xml', 'xml'),
    'Xz': ('XZ', 'application/x-xz', 'xz'),
    'Zlib': ('zlib stream', None, None),
    'Zstd': ('Zstandard', 'application/zstd', 'zst'),
}

# ``enum`` ignores a string literal written after a member, so without this
# ``FileKind.Png.__doc__`` would fall back to the class docstring and
# ``help(FileKind)`` would list a hundred and fourteen identical paragraphs.
# Assigning it explicitly is what makes the display names show up there.
for _name, _meta in _META.items():
    setattr(FileKind[_name], "__doc__", _meta[0])
