// Regenerates bindings/nodejs/_kinds.js and bindings/nodejs/_kinds.d.ts.
//
// The variant list is read out of src/magical/magic.rs rather than written here,
// because the list in this file and the list in the crate are the same list and
// there is no reason to keep two copies of it.
//
// What makes the indices load-bearing: FileKind is a fieldless enum, so
// `FileKind::Png as i32` is 0 and stays 0 only for as long as Png stays first in
// the declaration. JavaScript cannot see Rust's discriminants, so the order of
// that declaration *is* this file's ABI, and nothing at runtime would notice if
// it drifted. The check that notices is test/kinds.test.js, which compares all
// 114 names against the kind indices the compiled wasm module reports — so a
// reordered enum fails a test rather than silently mis-naming every format.
//
// The count is pinned because the project has a standing decision to keep it at
// 114, and a silent 115 is exactly the kind of change that should take a
// deliberate edit here rather than arrive by accident.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const bindingDir = join(scriptDir, "..");
const repoRoot = join(bindingDir, "..", "..");

const EXPECTED_KINDS = 114;
const ENUM_SOURCE = join(repoRoot, "src", "magical", "magic.rs");

// Reads the variant names out of `pub enum FileKind { ... }` in declaration order.
//
// Deliberately narrow: it takes lines that are a bare identifier with an
// optional trailing comma, which is what the declaration actually contains, and
// it skips the `// --- Section ---` comments. A variant with an attribute or a
// doc comment would be skipped rather than misread, and the count check below is
// what turns that into a loud failure instead of a shorter list.
function readEnumVariants(source) {
  const start = source.indexOf("pub enum FileKind {");
  if (start === -1) {
    throw new Error(`no \`pub enum FileKind\` in ${ENUM_SOURCE}`);
  }
  const body = source.slice(start);
  const end = body.indexOf("\n}");
  if (end === -1) {
    throw new Error(`\`pub enum FileKind\` in ${ENUM_SOURCE} is not closed`);
  }

  const variants = [];
  for (const line of body.slice(0, end).split("\n").slice(1)) {
    const match = /^\s*([A-Za-z_][A-Za-z0-9_]*)\s*,?\s*$/.exec(line);
    if (match) variants.push(match[1]);
  }
  return variants;
}

const variants = readEnumVariants(readFileSync(ENUM_SOURCE, "utf8"));

if (variants.length !== EXPECTED_KINDS) {
  throw new Error(
    `FileKind has ${variants.length} variants, expected ${EXPECTED_KINDS}.\n` +
      "The project keeps the format count fixed, so changing it is a decision:\n" +
      "update EXPECTED_KINDS here and the count in readme.md's coverage test, and\n" +
      "expect bindings/python/python/magical_py/_kinds.py to be regenerated too.",
  );
}

const seen = new Set();
for (const name of variants) {
  if (seen.has(name)) throw new Error(`duplicate variant ${name}`);
  seen.add(name);
}

// Two files, not one. `_kinds.js` is what Node runs and `_kinds.d.ts` is what
// TypeScript reads, and the split is a deliberate consequence rather than a
// convenience: `as const` and `export type` are TypeScript syntax, and they would
// be a SyntaxError in the `.js` Node actually loads. Collapsing the pair into one
// `.ts` would fix that by needing a build step and a loader — a whole toolchain
// added to a package whose entire point is that it has none.
const entries = variants.map((name, index) => `  ${name}: ${JSON.stringify(name)},`).join("\n");
const union = variants.map((name) => `  | ${JSON.stringify(name)}`).join("\n");
const lines = variants.map((name, index) => `  [${JSON.stringify(name)}, ${index}],`).join("\n");
const names = variants.map((name) => `  ${JSON.stringify(name)},`).join("\n");

const js = `// Generated by scripts/gen_kinds.mjs. Do not edit; run \`npm run gen\`.
//
// The names and their order come from \`pub enum FileKind\` in
// src/magical/magic.rs, because the order *is* the ABI: a file kind crosses the
// wasm boundary as its Rust discriminant, so entry N here is what the compiled
// module reports as N. test/kinds.test.js checks that against the real module.
//
// The types live in the .d.ts beside this file, not here: \`as const\` and
// \`export type\` are TypeScript syntax and would not parse here. A single .ts
// file would mean a build step, and this package ships no build.

/** Every format the built-in detection table can return, in the crate's own order. */
export const FileKind = {
${entries}
};

/**
 * Name to Rust discriminant, in the order the crate declares them.
 *
 * Exported because it is what turns a name into a call. The wasm side answers in
 * discriminants because that is all it can pass; this is where a name becomes
 * one.
 */
export const FILE_KIND_INDICES = new Map([
${lines}
]);

/**
 * Rust discriminant to name, indexed by that discriminant.
 *
 * The other direction, and the one the introspection API needs: the table arrives
 * from wasm as 114 anonymous integers, and each has to become a name. An array
 * rather than a reversed Map because this is read once per entry at import and
 * then never again.
 */
export const FILE_KIND_NAMES = Object.freeze([
${names}
]);
`;

const dts = `// Generated by scripts/gen_kinds.mjs. Do not edit; run \`npm run gen\`.

/** Every format the built-in detection table can return, in the crate's own order. */
export declare const FileKind: {
  readonly [K in FileKind]: K
}

/** The name of a format, as a TypeScript type. */
export type FileKind =
${union}

/**
 * Name to Rust discriminant, in the order the crate declares them.
 *
 * Exported because it is what turns a name into a call. The wasm side answers in
 * discriminants because that is all it can pass; this is where a name becomes
 * one.
 */
export declare const FILE_KIND_INDICES: ReadonlyMap<FileKind, number>

/**
 * Rust discriminant to name, indexed by that discriminant.
 *
 * The other direction, and the one the introspection API needs: the table arrives
 * from wasm as 114 anonymous integers, and each has to become a name. An array
 * rather than a reversed Map because this is read once per entry at import and
 * then never again.
 */
export declare const FILE_KIND_NAMES: readonly FileKind[]
`;

writeFileSync(join(bindingDir, "_kinds.js"), js, "utf8");
writeFileSync(join(bindingDir, "_kinds.d.ts"), dts, "utf8");

console.log(`gen_kinds: ${variants.length} variants`);
console.log(`  ${join(bindingDir, "_kinds.js")}`);
console.log(`  ${join(bindingDir, "_kinds.d.ts")}`);
