"""Tests for the ``FileKind`` enum and the metadata attached to it.

Metadata is generated by ``scripts/gen_kinds.ps1`` rather than typed
by hand, so these tests check the properties the generator is supposed to
guarantee rather than the contents of any one entry.
"""

from __future__ import annotations

import re

import pytest

from magical_py import FileKind

_MIME_PATTERN = re.compile(r"^[a-z]+/[A-Za-z0-9.+-]+$")


def test_every_member_has_metadata() -> None:
    for kind in FileKind:
        assert kind.description, f"{kind.name} has an empty description"
        assert kind.value, f"{kind.name} has an empty value"


def test_values_are_unique() -> None:
    """A duplicate value would silently collapse into an alias.

    ``Enum`` treats a repeated value as an alias for the member declared
    first, so the enum would quietly have fewer members than the detection
    table and the drift test would not notice.
    """
    values = [kind.value for kind in FileKind]
    assert len(values) == len(set(values))


def test_extension_has_no_leading_dot() -> None:
    for kind in FileKind:
        extension = kind.extension
        if extension is not None:
            assert not extension.startswith("."), f"{kind.name} extension has a dot"


def test_mime_is_well_formed_when_present() -> None:
    for kind in FileKind:
        mime = kind.mime
        if mime is not None:
            assert _MIME_PATTERN.match(mime), f"{kind.name} has malformed mime {mime!r}"


def test_from_value_round_trips() -> None:
    for kind in FileKind:
        assert FileKind.from_value(kind.value) is kind


def test_lookup_by_name() -> None:
    assert FileKind["Png"] is FileKind.Png
    with pytest.raises(KeyError):
        FileKind["NotARealFormat"]


def test_from_value_rejects_unknown() -> None:
    with pytest.raises(ValueError):
        FileKind.from_value("not-a-real-format")


def test_members_are_not_detected_by_content_alone() -> None:
    """The enum is a data table, so every member must be a real object.

    Guards against a generator bug that declared a member twice and produced
    an alias: ``len(FileKind)`` would still match, but iterating would yield
    a duplicate.
    """
    names = [kind.name for kind in FileKind]
    assert len(names) == len(set(names))
    assert all(kind is not None for kind in FileKind)


def test_description_is_a_display_name() -> None:
    """Descriptions come from the readme tables, so they are prose.

    This is a weak but cheap check that the readme was parsed rather than
    something else being written into the metadata table by mistake.
    """
    assert FileKind.Png.description == "PNG"
    assert FileKind.Gzip.description == "Gzip"
    assert FileKind.PkgZip.description == "Zip / JAR / APK"


def test_member_docstring_is_the_display_name() -> None:
    """``help(FileKind)`` should show a name, not 114 copies of the class doc.

    ``enum`` ignores a string literal written after a member, so without an
    explicit assignment ``FileKind.Png.__doc__`` falls back to the class
    docstring and the interactive help becomes useless.
    """
    for kind in FileKind:
        assert kind.__doc__ == kind.description, f"{kind.name} docstring is not its description"


def test_member_docstring_does_not_fall_back_to_the_class() -> None:
    """Guards the specific failure mode, independently of the metadata.

    A member with no doc of its own resolves ``__doc__`` through the enum
    class, so the check above would pass for the wrong reason if every
    description happened to equal the class docstring.
    """
    class_doc = FileKind.__doc__
    assert class_doc is not None
    for kind in FileKind:
        assert kind.__doc__ != class_doc
